name: Scheduled Publish

on:
  #schedule:
  #  - cron: '22 3 * * 0'
  workflow_dispatch:

env:
  BASE_DEVEL_IMG: base-devel
  LATEST_IMG: latest
  BASE_IMG: base

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  publish:
    runs-on: ubuntu-latest
    container:
      image: athenaos/base-devel:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo pacman -Sy --noconfirm --needed make docker devtools fakeroot fakechroot

      - name: Build base
        run: |
          make
          make image-base
          docker tag athenaos/base docker.io/athenaos/$BASE_IMG:$LATEST_IMG

      #- name: Build base-devel
      #  run: |
      #    make
      #    make image-base-devel
      #    docker tag athenaos/base-devel docker.io/athenaos/$BASE_DEVEL_IMG:$LATEST_IMG

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: |
          docker push docker.io/athenaos/$BASE_IMG:$LATEST_IMG
      #    docker push docker.io/athenaos/$BASE_DEVEL_IMG:$LATEST_IMG
